version: '2'

services:
  idrac1:
    image: ncerny/idrac
    restart: always
    ports:
      - 5800:5800
      - 5900:5900
    environment:
      - IDRAC_HOST=idrac1.example.org
      - IDRAC_USER=root
      - IDRAC_PASSWORD=1234
  idrac2:
    image: ncerny/idrac
    restart: always
    ports:
      - 5801:5800
      - 5901:5900
    environment:
      - IDRAC_HOST=idrac2.example.org
      - IDRAC_USER=root
      - IDRAC_PASSWORD=1234
